# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fhTAsHCtVkK7M4g_mDTTxjGhRz-JppSm
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.linspace(0, 10, 200)

y = np.sin(x)

plt.plot(x, y)
plt.xlabel("x")
plt.ylabel("y")
plt.title("My first Python simulation")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

N = 50

fluid = np.zeros((N, N))

plt.imshow(fluid)
plt.title("Empty 2D Fluid Grid")
plt.colorbar()
plt.show()

fluid[25, 25] = 1

plt.imshow(fluid)
plt.title("A Small Amount of Fluid")
plt.colorbar()
plt.show()

new_fluid = fluid.copy()

for i in range(1, N - 1):
    for j in range(1, N - 1):
            new_fluid[i, j] = (
                        fluid[i, j] +
                                    fluid[i+1, j] +
                                                fluid[i-1, j] +
                                                            fluid[i, j+1] +
                                                                        fluid[i, j-1]
                                                                                ) / 5

fluid = new_fluid

plt.imshow(fluid)
plt.title("Fluid Spreading")
plt.colorbar()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Size of our 2D grid
N = 50

# Amount of fluid/dye in each cell
fluid = np.zeros((N, N))

# Put some fluid in the center
fluid[25, 25] = 1

# Horizontal velocity
velocity_x = np.zeros((N, N))

# Vertical velocity
velocity_y = np.zeros((N, N))

# Give the fluid a horizontal velocity
velocity_x[:, :] = 1

print("Grid size:", fluid.shape)
print("Fluid at center:", fluid[25, 25])
print("Horizontal velocity at center:", velocity_x[25, 25])
print("Vertical velocity at center:", velocity_y[25, 25])

import numpy as np
import matplotlib.pyplot as plt

fluid = np.zeros((50, 50))

fluid[25, 10] = 1

for step in range(20):
    fluid = np.roll(fluid, 1, axis=1)

    fluid[:, 0] = 0

    plt.imshow(fluid)
    plt.title("Fluid Moving to the Right")
    plt.colorbar()
    plt.show()

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

fluid = np.zeros((50, 50))
fluid[25, 5] = 1

for step in range(40): fluid = np.roll(fluid, 1, axis=1); fluid[:, 0] = 0; clear_output(wait=True); plt.imshow(fluid); plt.title("Fluid Moving"); plt.colorbar(); plt.show(); time.sleep(0.1)

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

N = 80
fluid = np.zeros((N, N))

for step in range(80): fluid[:, 2] = 1.0; fluid = np.roll(fluid, 1, axis=1); fluid[:, 0] = 0; clear_output(wait=True); plt.imshow(fluid, origin="lower"); plt.title("2D Fluid Flow"); plt.colorbar(); plt.show(); time.sleep(0.05)

import numpy as np
import matplotlib.pyplot as plt
from IPython.display import clear_output
import time

N = 80
fluid = np.zeros((N, N))

# Obstacle in the middle
obstacle = np.zeros((N, N), dtype=bool)
obstacle[25:55, 40] = True

for step in range(80): fluid[:, 2] = 1.0; fluid[obstacle] = 0; fluid = np.roll(fluid, 1, axis=1); fluid[:, 0] = 0; clear_output(wait=True); plt.imshow(fluid, origin="lower"); plt.title("Fluid Flow Around an Obstacle"); plt.colorbar(); plt.show(); time.sleep(0.05)

import numpy as np
import matplotlib.pyplot as plt

N = 30

# Velocity in the horizontal direction
u = np.ones((N, N))

# Velocity in the vertical direction
v = np.zeros((N, N))

# Make a grid of positions
x, y = np.meshgrid(np.arange(N), np.arange(N))

# Draw the velocity arrows
plt.figure(figsize=(8, 8))
plt.quiver(x, y, u, v)

plt.title("Velocity Field")
plt.xlabel("x position")
plt.ylabel("y position")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

N = 30

# Create the grid
x, y = np.meshgrid(np.arange(N), np.arange(N))

# Start with flow to the right
u = np.ones((N, N))
v = np.zeros((N, N))

# Position of the obstacle
cx = 15
cy = 15
radius = 5

# Distance from the obstacle
distance = np.sqrt((x - cx)**2 + (y - cy)**2)

# Make the flow turn around the obstacle
v = 3 * (y - cy) / (distance + 1)

# Stop the arrows inside the obstacle
obstacle = distance < radius
u[obstacle] = 0
v[obstacle] = 0

# Draw the velocity field
plt.figure(figsize=(8, 8))
plt.quiver(x, y, u, v)

# Draw the obstacle
circle = plt.Circle((cx, cy), radius, fill=False)
plt.gca().add_patch(circle)

plt.xlim(0, N)
plt.ylim(0, N)
plt.gca().set_aspect("equal")
plt.title("Velocity Field Around an Obstacle")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

N = 30

# Create the grid
x, y = np.meshgrid(np.arange(N), np.arange(N))

# Create a simple pressure field
pressure = np.exp(-((x - 15)**2 + (y - 15)**2) / 30)

# Display pressure
plt.figure(figsize=(8, 6))
plt.imshow(pressure, origin="lower")

plt.colorbar(label="Pressure")
plt.title("Pressure Field")
plt.xlabel("x position")
plt.ylabel("y position")

plt.show()

import numpy as np
import matplotlib.pyplot as plt

N = 50
u = np.zeros((N, N))

u[20:30, :] = 5

viscosity = 0.1

a = np.roll(u, 1, axis=0)
b = np.roll(u, -1, axis=0)
c = np.roll(u, 1, axis=1)
d = np.roll(u, -1, axis=1)

u = u + viscosity * (a + b + c + d - 4*u)

plt.imshow(u, origin="lower")
plt.colorbar(label="Velocity")
plt.title("Effect of Viscosity")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

N = 50

# Pressure is higher on the left
pressure = np.zeros((N, N))
pressure[:, 0:10] = 10

# Calculate pressure difference in the x direction
pressure_gradient = np.gradient(pressure, axis=1)

# Pressure pushes fluid away from high pressure
velocity = -pressure_gradient

plt.imshow(velocity, origin="lower")
plt.colorbar(label="Velocity caused by pressure")
plt.title("Pressure Producing Fluid Motion")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Size of our 2D box
N = 50

# Velocity of the fluid at every point
u = np.zeros((N, N))

# Make the middle region move quickly
u[20:30, :] = 5

# Show the initial velocity
plt.imshow(u, origin="lower")
plt.colorbar(label="Velocity")
plt.title("Initial fluid velocity")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter

N = 50

u = np.zeros((N, N))

# Fast-moving fluid in the middle
u[20:30, :] = 5

# Viscosity spreads the velocity
u = gaussian_filter(u, sigma=3)

plt.imshow(u, origin="lower")
plt.colorbar(label="Velocity")
plt.title("Viscosity spreading fluid motion")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.ndimage import gaussian_filter
from IPython.display import clear_output
import time

N = 50
u = np.zeros((N, N))

# Fast-moving layer
u[20:30, :] = 5

for step in range(20):

    u = gaussian_filter(u, sigma=0.8)

        clear_output(wait=True)

            plt.imshow(u, origin="lower")
                plt.colorbar(label="Velocity")
                    plt.title("Viscosity spreading motion")
                        plt.show()

                            time.sleep(0.15)